<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260911210239 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE aianalysis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, summary TEXT DEFAULT NULL, suggested_priority VARCHAR(20) DEFAULT NULL, suggested_category VARCHAR(100) DEFAULT NULL, keywords JSON DEFAULT NULL, suggestions JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_487E289E700047D2 ON aianalysis (ticket_id)');
        $this->addSql('ALTER TABLE aianalysis ADD CONSTRAINT FK_487E289E700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE aianalysis DROP CONSTRAINT FK_487E289E700047D2');
        $this->addSql('DROP TABLE aianalysis');
    }
}
