<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261004222000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align conversation table identifiers with Doctrine PostgreSQL identity mappings.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ticket_message ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE ticket_message_id_seq');
        $this->addSql('ALTER TABLE ticket_message ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');

        $this->addSql('ALTER TABLE knowledge_article ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE knowledge_article_id_seq');
        $this->addSql('ALTER TABLE knowledge_article ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ticket_message ALTER id DROP IDENTITY');
        $this->addSql('CREATE SEQUENCE ticket_message_id_seq');
        $this->addSql("ALTER TABLE ticket_message ALTER id SET DEFAULT nextval('ticket_message_id_seq')");
        $this->addSql('ALTER SEQUENCE ticket_message_id_seq OWNED BY ticket_message.id');
        $this->addSql("SELECT setval('ticket_message_id_seq', COALESCE((SELECT MAX(id) FROM ticket_message), 1), EXISTS (SELECT 1 FROM ticket_message))");

        $this->addSql('ALTER TABLE knowledge_article ALTER id DROP IDENTITY');
        $this->addSql('CREATE SEQUENCE knowledge_article_id_seq');
        $this->addSql("ALTER TABLE knowledge_article ALTER id SET DEFAULT nextval('knowledge_article_id_seq')");
        $this->addSql('ALTER SEQUENCE knowledge_article_id_seq OWNED BY knowledge_article.id');
        $this->addSql("SELECT setval('knowledge_article_id_seq', COALESCE((SELECT MAX(id) FROM knowledge_article), 1), EXISTS (SELECT 1 FROM knowledge_article))");
    }
}
