<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260911211413 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ticket_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, old_value TEXT DEFAULT NULL, new_value TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, changed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B762919700047D2 ON ticket_history (ticket_id)');
        $this->addSql('CREATE INDEX IDX_2B762919828AD0A0 ON ticket_history (changed_by_id)');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919700047D2');
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919828AD0A0');
        $this->addSql('DROP TABLE ticket_history');
    }
}
